-- dofile("api.lua")
local window = core.newWindow("Test Window", 800, 600)
print( string.format("New window: \t%08x", window) )
local renderer = core.newRenderer(window, 0)
print( string.format("New renderer: \t%08x", renderer) )
core.destroyRenderer(renderer)
core.destroyWindow(window)